services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: shivanshos_npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  qdrant:
    image: qdrant/qdrant:latest
    container_name: shivanshos_qdrant
    restart: unless-stopped
    ports:
      - '6333:6333'
    volumes:
      - /opt/shivanshos/vector_db/qdrant_data:/qdrant/storage

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: shivanshos_webui
    restart: unless-stopped
    ports:
      - '3000:8080'
    environment:
      - OLLAMA_BASE_URL=http://172.17.0.1:11434
      - WEBUI_SECRET_KEY=shivanshos_secure_secret_2026
    volumes:
      - /opt/shivanshos/gateway/webui_data:/app/backend/data
